<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= htmlspecialchars($title ?? 'Surat') ?></title>
    <style>
        @media print {
            body {
                font-family: Times New Roman, serif;
                line-height: 1.6;
                margin: 20px;
                font-size: 12pt;
            }
            .no-print {
                display: none !important;
            }
        }
        @media screen {
            body {
                font-family: Times New Roman, serif;
                line-height: 1.6;
                margin: 20px;
                font-size: 12pt;
                background: #f5f5f5;
            }
            .print-container {
                background: white;
                padding: 40px;
                max-width: 800px;
                margin: 20px auto;
                box-shadow: 0 0 10px rgba(0,0,0,0.1);
            }
        }
        table {
            border-collapse: collapse;
            width: 100%;
        }
        table td {
            padding: 5px;
        }
        .text-center {
            text-align: center;
        }
        .text-right {
            text-align: right;
        }
        .font-weight-bold {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="print-container">
        <div class="no-print" style="text-align: center; margin-bottom: 20px;">
            <button onclick="window.print()" class="btn btn-primary">
                <i class="bi bi-printer"></i> Cetak Surat
            </button>
            <button onclick="window.close()" class="btn btn-secondary">
                <i class="bi bi-x-circle"></i> Tutup
            </button>
        </div>
        
        <?= $content ?>
        
        <div class="no-print" style="text-align: center; margin-top: 20px; font-size: 11px; color: #666;">
            <p>Generated by KSP Lam Gabe Jaya - <?= date('d/m/Y H:i') ?></p>
        </div>
    </div>
    
    <script>
        // Auto print dialog
        window.onload = function() {
            if (window.confirm('Apakah Anda ingin mencetak surat ini?')) {
                window.print();
            }
        };
    </script>
</body>
</html>
